config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('lecture.urls')),
]

lecture/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import HomeView, EventView, applied_events, past_events, upcoming_events, event_registration_view

app_name = "lecture_app"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("applied_events/<int:user_pk>/", applied_events, name="applied_events"),
    path("upcoming_events/<int:user_pk>/", upcoming_events, name="upcoming_events"),
    path("past_events/<int:user_pk>/", past_events, name="past_events"),
    path("<int:user_pk>/event/<int:pk>/", EventView.as_view(), name="event"),
    path("<int:user_pk>/event/<int:pk>/register", event_registration_view, name="event_registration"),
]

templates/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Default Title{% endblock %}</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.1.1/bootstrap-social.min.css"
        integrity="sha512-f8mUMCRNrJxPBDzPJx3n+Y5TC5xp6SmStstEfgsDXZJTcxBakoB5hvPLhAfJKa9rCvH+n3xpJ2vQByxLk4WP2g=="
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
        integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
        crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/_base.css' %}">


    {% block head %}{% endblock %}


</head>

<body>

    {% block nav %}
    <nav class="navbar navbar-expand-lg navbar-extend-sm navbar-dark bg-dark" id="MyNav">
        <div class="container">
            <a class="navbar-brand" id="univLogo" href="{% url 'lecture_app:home'   %}"><span class="fas fa-university">
                    Event System</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id='Navbar'>
                <div class="navbar-nav">
                    {% comment %} <a class="nav-item nav-link {% if request.path == '/' %}active{% endif %}"
                        href="{% url 'lecture_app:home'   %}"><span class="fas fa-user-graduate"></span> My
                        Details</a> {% endcomment %}
                    <a class="nav-item nav-link {% if request.path == 'courses' %}active{% endif %}"
                        href="{% url 'lecture_app:home'   %}"><span class="fas fa-book-open"></span>
                        Events</a>
                    {% comment %} <a class="nav-item nav-link {% if request.path == 'exams' %}active{% endif %}"
                        href="{% url 'lecture_app:home'   %}"><span class="fas fa-edit"></span> Settings</a> {% endcomment %}
                    <a class="nav-item nav-link {% if request.path == 'scores' %}active{% endif %}"
                        href="{% url 'lecture_app:home'%}"><span class="fas fa-clock"></span> 
                        <span id='current_time'>{% now "jS F Y H:i" %}</span>
                            <script src={% static 'js/refresh_time.js' %} type="text/javascript">
                            </script>
                    </a>
                </div>
                <div class="navbar-text ml-auto justify-content-right">
                    <a class="nav-item nav-link"
                        href="{% url 'lecture_app:home' %}">
                        <span class="fas fa-user-graduate"></span> {{ user.username }}</a>

                    </span>
                </div>


                <div class="navbar-nav">
                    <a class="nav-item nav-link ml-auto" href="{% url 'logout' %}">
                    <span class="fas fa-sign-out-alt"></span> Log Out</a>
                </div>
            </div>
        </div>
    </nav>
    {% endblock %}

    {% block content %}
    {% endblock %}

    <!-- Footer -->
    <footer class="">

        {% comment %} 
        <!-- Copyright -->
        <div class="justify-content-center navbar fixed-bottom">
            © {% now "Y" %} Copyright:<a href="https://github.com/hiruthikj/guest-lecture"> University</a>
        </div> 
        {% endcomment %}

    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous">
    </script>

</body>

</html>

templates/_event_list.html
<!-- Background image -->
{% for event in events %}
<div class="card text-center justify-content-center text-md-center" style="max-width: 50%; margin: auto; margin-bottom:20px;">
    <div class="card-header">
        {{ event.type }}
    </div>
    <div class="card-body">
        <h5 class="card-title">{{ event.event_name }}</h5>
        <p class="card-text">{{ event.description }}</p>
        <a href="{% url 'lecture_app:event' user.id event.id %}" class="btn btn-primary">link to the event page</a>
    </div>
    <div class="card-footer text-muted">
        <p>Starts on {{ event.start_date }}</p>
        <p>Ending on {{ event.end_date }}</p>
        
    </div>
</div>
{% endfor %}

templates/_mail_template_style.html
.styled-table {
  border-collapse: collapse;
  margin: 25px 0;
  font-size: 0.9em;
  font-family: sans-serif;
  min-width: 400px;
  box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
}

.styled-table thead tr {
  background-color: #009879;
  color: #ffffff;
  text-align: left;
}

.styled-table th,
.styled-table td {
  padding: 12px 15px;
}

.styled-table tbody tr {
  border-bottom: 1px solid #dddddd;
}

.styled-table tbody tr:nth-of-type(even) {
  background-color: #f3f3f3;
}

.styled-table tbody tr:last-of-type {
  border-bottom: 2px solid #009879;
}

.styled-table tbody tr.active-row {
  font-weight: bold;
  color: #009879;
}

templates/appliedEvents.html
{% extends '_base.html' %}
{% load static %} 

{% block title %}Event List{% endblock title %}

{% block content %}


<div class="container">
    <div class="display-3 text-align">Applied Events</div><br>
    {% include '_event_list.html' %}
</div>  


{% endblock content %}

templates/applied_events.html
{% extends '_base.html' %}
{% load static %} 

{% block title %}Event List{% endblock title %}

{% block content %}


<div class="container">
    <div class="display-3 text-align">Applied Events</div><br>
    {% include '_event_list.html' %}
</div>  


{% endblock content %}

templates/event.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Event - {{ event.event_name }}{% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/event.css' %}">
{% endblock head %}


{% block content %}

  <div class="container">
  <div class="display-3 text-align">{{ event.event_name }}</div><br>


  <!-- Classic tabs -->
  <div class="background-white">
    <div class="classic-tabs border rounded px-4 pt-1">

      <ul class="nav tabs-primary nav-justified bg-dark" id="advancedTab" role="tablist">
        <li class="nav-item">
          <a class="nav-link" id="description-tab" data-toggle="tab" href="#description" role="tab"
            aria-controls="description">Description</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="info-tab" data-toggle="tab" href="#info" role="tab"
            aria-controls="info">Information</a>
        </li>
        {% if event.is_past_event %}
        <li class="nav-item">
          <a class="nav-link" id="reviews-tab" data-toggle="tab" href="#reviews" role="tab"
            aria-controls="reviews">Reviews (1)</a>
        </li>
        {% endif %}

      </ul>
      <div class="tab-content" id="advancedTabContent">
        <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="description-tab">
          <h5>Lecturer</h5>
          <p> <span class="fas fa-user-tie text-info"></span> {{ event.guest_fk.get_name }} </p>
          <p class="small text-muted text-uppercase mb-2">{{ event.guest_fk.details }}</p>

          <br>
          <h6><em>{{ event.type }}</em> event</h6>

          {% if event.max_seats %}
          {% comment %} <h6>Maximum Seats <span class="fas fa-user-alt text-warning"></span> {{ event.max_seats }}</h6> {% endcomment %}
          {% endif %}
          <p class="pt-1"> {{ event.description }} </p>
        </div>
        <div class="tab-pane fade" id="info" role="tabpanel" aria-labelledby="info-tab">
          <h5>Additional Information</h5>
          <table class="table table-striped table-bordered mt-3" aria-describedby="Additional Information">
            <thead>
              <tr>
                <th scope="row" class="w-150 dark-grey-text h6">Start</th>
                <td> <span class="fas fa-calendar text-info"></span> {{ event.start_date }}</td>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row" class="w-150 dark-grey-text h6">End</th>
                <td> <span class="far fa-calendar text-info"></span> {{ event.end_date }}</td>
              </tr>
              <tr>
                <th scope="row" class="w-150 dark-grey-text h6">Location</th>
                <td> <span class="fas fa-map-marker-alt text-danger"></span> {{ event.place }}</td>
              </tr>
              {% if event.max_seats and event.occupied_seats and event.is_seats_full %}
              <tr>
                <th scope="row" class="w-150 dark-grey-text h6">Remaining Seats</th>
                <td><span class="fas fa-user-alt text-warning"> {{ event.remaining_seats }} / {{ event.max_seats }}</td>
              </tr>
              {% endif %}
            </tbody>
          </table>
        </div>
        {% if event.is_past_event %}
        <div class="tab-pane fade" id="reviews" role="tabpanel" aria-labelledby="reviews-tab">
          <h5><span>1</span> review for <span>Fantasy T-shirt</span></h5>
          <div class="media mt-3 mb-4">
            <img class="d-flex mr-3 z-depth-1" src="https://mdbootstrap.com/img/Photos/Others/placeholder1.jpg"
              width="62" alt="Generic placeholder image">
            <div class="media-body">
              <div class="d-sm-flex justify-content-between">
                <p class="mt-1 mb-2">
                  <strong>Marthasteward </strong>
                  <span>– </span><span>January 28, 2020</span>
                </p>
                <ul class="rating mb-sm-0">
                  <span class="fas fa-star fa-sm text-primary"></span>
                  <span class="fas fa-star fa-sm text-primary"></span>
                  <span class="fas fa-star fa-sm text-primary"></span>
                  <span class="fas fa-star fa-sm text-primary"></span>
                  <span class="far fa-star fa-sm text-primary"></span>
                </ul>
              </div>
              <p class="mb-0">Nice one, love it!</p>
            </div>
          </div>
          <hr>
          <h5 class="mt-4">Add a review</h5>
          <p>Your email address will not be published.</p>
          <div class="my-3">
            <ul class="rating mb-0">
              <a href="#!">
                <span class="fas fa-star fa-sm text-primary"></span>
              </a>
              <a href="#!">
                <span class="fas fa-star fa-sm text-primary"></span>
              </a>
              <a href="#!">
                <span class="fas fa-star fa-sm text-primary"></span>
              </a>
              <a href="#!">
                <span class="fas fa-star fa-sm text-primary"></span>
              </a>
              <a href="#!">
                <span class="far fa-star fa-sm text-primary"></span>
              </a>
            </ul>
          </div>
          <div>
            <!-- Your review -->
            <div class="md-form md-outline">
              <label for="form76">Your review</label>
              <textarea id="form76" class="md-textarea form-control pr-6" rows="4"></textarea>
            </div>
            {% comment %}
            <!-- Name -->
            <div class="md-form md-outline">
              <input type="text" id="form75" class="form-control pr-6">
              <label for="form75">Name</label>
            </div>
            <!-- Email -->
            <div class="md-form md-outline">
              <input type="email" id="form77" class="form-control pr-6">
              <label for="form77">Email</label>
            </div>
            {% endcomment %}
            <div class="text-right pb-2">
              <button type="button" class="btn btn-primary">Add </button>
            </div>
          </div>
        </div>
        {% endif %}
      </div>
      {% if already_applied %}
      <button type="submit" class="btn btn-outline-success disabled text-align" aria-disabled="true">Registered
        Sucessfully</button>
      {% elif event.max_seats and event.occupied_seats and event.is_seats_full %}
      <button type="submit" class="btn btn-outline-danger disabled text-align" aria-disabled="true">No seat available</button>
      {% else %}
      <form action="{% url 'lecture_app:event_registration' user_pk=user.pk pk=event.pk %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary text-align">Register</button>
      </form>
      {% endif %}
    </div>
    <!-- Classic tabs -->
  </div>
</div>



{% endblock content %}

templates/home.html
{% extends '_base.html' %}
{% load static %} 

{% block title %}Home{% endblock title %} 

{% block head %} 
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock head %} 

{% block content %}


<!-- Background image -->
<div class="p-5 text-center bg-image my-bg-img" >
    <div class="mask" style="background-color: rgba(0, 0, 0, 0.6)">
        <div class="justify-content-center align-items-center h-100">
            <div class="text-white">
                <h1 class="mb-3">Welcome to the Event System, {{ user.username }}!</h1>
                {% comment %}
                <h4 class="mb-3">Subheading</h4> {% endcomment %} {% comment %} <a class="btn btn-outline-light btn-lg" href="#!" role="button">Call to action</a> 
                {% endcomment %} 
                {% comment %} {% if user.user_type == "STUD" %} {% endcomment %}
                <div class="container justify-content-center w-25">
                    <div class="card">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item bg-success ">
                                <p class="">
                                    Applied Events
                                    <a href="{% url 'lecture_app:applied_events' user.id %}" class="stretched-link float-right"><span class="fas fa-angle-double-right"></span></a>
                                </p>
                            </li>
                            <li class="list-group-item bg-info ">
                                <p class="">
                                    Upcoming Events
                                    <a href="{% url 'lecture_app:upcoming_events' user.id %}" class="stretched-link float-right"><span class="fas fa-angle-double-right"></span></a>
                                </p>
                            </li>
                            <li class="list-group-item bg-warning ">
                                <p class="">
                                    Past Events
                                    <a href="{% url 'lecture_app:past_events' user.id %}" class="stretched-link float-right"><span
                                            class="fas fa-angle-double-right"></span></a>
                                </p>
                            </li>
                        </ul>
                    </div>
                </div>
                {% comment %} {% else %}
                <div class="container justify-content-center w-25">
                    <div class="card">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item bg-success ">
                                <p class="">

                                    Create an Event
                                    <a href="/applied_events/{{ user.id }}" class="stretched-link float-right"><span
                                            class="fas fa-angle-double-right"></span></a>
                                </p>
                            </li>
                            <li class="list-group-item bg-info ">
                                <p class="">

                                    Created Events
                                    <a href="/upcoming_events/{{ user.id }}" class="stretched-link float-right"><span
                                            class="fas fa-angle-double-right"></span></a>
                                </p>
                            </li>
                            <li class="list-group-item bg-warning ">
                                <p class="">

                                    Past Events
                                    <a href="{% url 'lecture_app:past_events' user.id %}" class="stretched-link float-right"><span
                                            class="fas fa-angle-double-right"></span></a>
                                </p>
                            </li>
                        </ul>
                    </div>
                </div>

                {% endif %} {% endcomment %}

            </div>
        </div>
    </div>
</div>
<!-- Background image -->


{% endblock content %}

templates/mail_template.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
      <style>
        {% include '_mail_template_style.html' %}
      </style>
  </head>

  <body style="text-align: justify;">
    <h2>Hello <strong>{{user}}</strong>!</h2>
    You have applied to
    <em>{{event}}</em> successfuly!<br>

    <h3>Event Information</h3>

    <table class="styled-table">
      <tbody>
        <tr>
          <th>Start  </th>
          <td>{{event.start_date}}</td>
        </tr>
        <tr>
          <th>End  </th>
          <td>{{event.end_date}}</td>
        </tr>
        <tr>
          <th>Location  </th>
          <td>{{event.place}}</td>
        </tr>
      </tbody>
    </table>
  </body>
</html>

templates/pastEvents.html
{% extends '_base.html' %}
{% load static %} 

{% block title %}Event List{% endblock title %}

{% block content %}

<div class="container">
    <div class="display-3 text-align">Past Events</div><br>
    {% include '_event_list.html' %}
</div>

{% endblock content %}

templates/past_events.html
{% extends '_base.html' %}
{% load static %} 

{% block title %}Event List{% endblock title %}

{% block content %}

<div class="container">
    <div class="display-3 text-align">Past Events</div><br>
    {% include '_event_list.html' %}
</div>

{% endblock content %}

templates/signup.html
{% extends '_base.html' %} 
{% load static %} 

{% block title %}Sign Up{% endblock%} 
{% block head %}
  <link rel="stylesheet" href="{% static 'css/signup.css' %}" />
{% endblock %} 
{% block nav %} {% endblock %} 

{% block content %}
<div class="container">
  <div class="card card-container form-group">
    <p id="profile-name" class="profile-name-card">
      <img src="{% static 'img/university.svg' %}" alt="university logo" />
    </p>
    <h1 id="pageTitle">LECTURE SYSTEM</h1>

    <form action="{% url 'signup' %}" method="post" class="form-signin">
      {% csrf_token %} 
      {% for field in form %}
      <p>
        {{ field.label_tag }}<br />
        {{ field }} 
        
          {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
          {% endif %} 

        {% for error in field.errors %}
        <button type="button" class="btn btn-danger" disabled id="invalidPwd">
          {{ error }}
        </button>
        {% endfor %}
      </p>
      {% endfor %}

      <!--<label><input name="remember_me" type="checkbox">Keep me logged in</label> -->
      <button
        type="submit"
        name="submit"
        class="btn btn-lg btn-primary btn-block btn-signin"
      >
        Sign up
      </button>
    </form>

    <span class="margin-0-auto">Have account? <a href="{% url 'login' %}">Login</a></span>
  </div>
</div>

{% endblock %}

templates/signup_success.html
{% extends '_base.html' %}
{% load static %}

{% block title %}LOGOOUT{% endblock %}

{% block head %}
{% comment %} <link rel="stylesheet" href="{% static 'css/login.css' %}"> {% endcomment %}
<link rel="stylesheet" href="{% static 'css/logout.css' %}">

{% endblock %}

{% block nav %}
{% endblock %}

{% block content %}    
<div class="container">
    <div class="card card-container form-group">
        <p id="profile-name" class="profile-name-card"><img src="{% static 'img/university.svg' %}" alt="university logo"></p>

        <h4 class="logoutMessage">You have signed up sucessfully</h4>
        <a href="{% url 'login' %}">
            <button type="submit" class="btn btn-lg btn-primary btn-block btn-signin">Login Now</button>
        </a>
    </div>
</div>

{% endblock %}

templates/upcomingEvents.html
{% extends '_base.html' %}
{% load static %} 

{% block title %}Event List{% endblock title %}

{% block content %}

<div class="container">
    <div class="display-3 text-align">Upcoming Events</div><br>
    {% include '_event_list.html' %}
</div>

{% endblock content %}

templates/upcoming_events.html
{% extends '_base.html' %}
{% load static %} 

{% block title %}Event List{% endblock title %}

{% block content %}

<div class="container">
    <div class="display-3 text-align">Upcoming Events</div><br>
    {% include '_event_list.html' %}
</div>

{% endblock content %}